[build]
  command = "npm run build"
  publish = "build"

[functions]
  node_bundler = "esbuild"
  
[headers]
  for = "/*.webmanifest"
  [headers.values]
    Content-Type = "application/xml appinstaller"
    Content-Type = "application/vns.ms-appx appxbundle appx"
