// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'fr'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	header: {
		/**
		 * Home
		 */
		home: string
		/**
		 * Docs
		 */
		docs: string
		/**
		 * Blog
		 */
		blog: string
	}
	footer: {
		/**
		 * Pages
		 */
		pages: string
		/**
		 * Home
		 */
		home: string
		/**
		 * Documentation
		 */
		documentation: string
		/**
		 * Blog
		 */
		blog: string
		/**
		 * Contribute to Files
		 */
		contributeToFiles: string
		/**
		 * Give Feedback
		 */
		giveFeedback: string
		/**
		 * Style Guide
		 */
		styleGuide: string
		/**
		 * Translations
		 */
		translations: string
		/**
		 * Contribute to this site
		 */
		contributeToSite: string
		/**
		 * GitHub Repo
		 */
		gitHubRepo: string
		/**
		 * Found a bug?
		 */
		foundBug: string
		/**
		 * Web Team
		 */
		webTeam: string
		/**
		 * Copyright © 2021 - {thisYear}, The Files Authors
		 * @param {unknown} thisYear
		 */
		copyright: RequiredParams<'thisYear'>
		/**
		 * GitHub repository
		 */
		gitHubRepository: string
		/**
		 * Twitter profile
		 */
		twitterProfile: string
		/**
		 * Discord server
		 */
		discordServer: string
	}
	section: {
		download: {
			/**
			 * Downloading...
			 */
			downloading: string
			/**
			 * Thank you for downloading Files!
			 */
			thankYou: string
			/**
			 * If the download hasn't started yet, press {link} to start it:
			 * @param {unknown} link
			 */
			comment: RequiredParams<'link'>
			/**
			 * here
			 */
			here: string
			/**
			 * Firefox adds a <code>.xml</code> file extension to the downloaded installer. Remove it before opening the installer.
			 */
			firefoxMessage: string
			/**
			 * Want to support the creators of Files?
			 */
			wantSupport: string
			/**
			 * Donate
			 */
			donate: string
		}
		hero: {
			/**
			 * A modern file explorer that pushes the boundaries of the platform.
			 */
			hook: string
			/**
			 * Download Files
			 */
			downloadFiles: string
			/**
			 * Choose download source
			 */
			downloadSource: string
			/**
			 * View GitHub
			 */
			viewGitHub: string
			/**
			 * Files is open source!
			 */
			openSource: string
			winget: {
				/**
				 * Installing Files via winget
				 */
				title: string
				/**
				 * To download and install Files using {link}, paste the following command into a terminal of your choice:
				 * @param {unknown} link
				 */
				description: RequiredParams<'link'>
				/**
				 * Copy Command
				 */
				copyCommand: string
				/**
				 * Copy
				 */
				copy: string
				/**
				 * Copied!
				 */
				copied: string
				/**
				 * Close
				 */
				close: string
			}
		}
		design: {
			/**
			 * design
			 */
			title: string
			/**
			 * Power meets beauty.
			 */
			hook: string
			/**
			 * Explore a beautiful Windows-first design. Manage all your files with increased productivity. Work across multiple folders with tabs. And so much more.
			 */
			description: string
			/**
			 * Try it out
			 */
			tryItOut: string
			/**
			 * Design System
			 */
			designSystem: string
		}
		features: {
			/**
			 * features
			 */
			title: string
			/**
			 * It already does that.
			 */
			hook: string
			/**
			 * Cloud files integration? Tabs and multiple layouts? Rich file previews? Files has it covered with robust features you expect from a modern file manager.
			 */
			description: string
			preview: {
				/**
				 * Name
				 */
				name: string
				/**
				 * Status
				 */
				status: string
				/**
				 * Tag
				 */
				tag: string
				/**
				 * Bit Depth
				 */
				bitDepth: string
				/**
				 * Dimensions
				 */
				dimensions: string
				/**
				 * Horizontal Resolution
				 */
				horizontalResolution: string
				/**
				 * Vertical Resolution
				 */
				verticalResolution: string
				/**
				 * Item Count
				 */
				itemCount: string
				/**
				 * Line Count
				 */
				lineCount: string
				/**
				 * Path
				 */
				path: string
				/**
				 * Date Created
				 */
				dateCreated: string
				/**
				 * Date Modified
				 */
				dateModified: string
				/**
				 * Blue
				 */
				blueTag: string
				/**
				 * Yellow
				 */
				yellowTag: string
				/**
				 * Green
				 */
				greenTag: string
				/**
				 * Gray
				 */
				grayTag: string
				/**
				 * Orange
				 */
				orangeTag: string
			}
			cards: {
				cloud: {
					/**
					 * Seamless cloud integration
					 */
					title: string
					/**
					 * Integration with cloud services such as OneDrive, Google Drive, and iCloud allow you to manage your documents and photos in the cloud, right from the sidebar.
					 */
					description: string
				}
				preview: {
					/**
					 * File preview
					 */
					title: string
					/**
					 * Preview documents, photos, and more without opening them. Support for rich previews, syntax highlighting, markdown and video playback is all built in.
					 */
					description: string
				}
				tag: {
					/**
					 * Tagged Files & Folders
					 */
					title: string
					/**
					 * Quickly mark and organize your files and folders for later by assigning them colored and named tags for easy identification. You can even add your own custom tags!
					 */
					description: string
				}
				tabs: {
					/**
					 * Multitask with tabs
					 */
					title: string
					/**
					 * Avoid multiple windows and keep your desktop clutter-free. Files features a browser-like tabbing interface complete with keyboard shortcuts.
					 */
					description: string
				}
			}
		}
		themes: {
			/**
			 * themes
			 */
			title: string
			/**
			 * Distinctly personal.
			 */
			hook: string
			/**
			 * Have it your way. Files features a fully customizable user interface, right down to the colors and materials. Try custom themes that are built into Files or dive right into the docs and create your own.
			 */
			description: string
			color: {
				/**
				 * Dark Grey • Light Blue
				 */
				darkGreyLightBlue: string
				/**
				 * Blue Grey • Neon Green
				 */
				blueGreyNeonGreen: string
				/**
				 * Purple
				 */
				purple: string
				/**
				 * Yellow • White
				 */
				yellowWhite: string
				/**
				 * Cool White • Dark Teal
				 */
				coolWhiteDarkTeal: string
				/**
				 * Sky Blue
				 */
				skyBlue: string
			}
		}
		community: {
			/**
			 * community
			 */
			title: string
			/**
			 * Designed and developed by you.
			 */
			hook: string
			/**
			 * Files is free and open source software, maintained and designed by a collective of hundreds of contributors.
			 */
			description: string
			/**
			 * Join the discussion
			 */
			joinDiscussion: string
			/**
			 * Become a contributer
			 */
			becomeContributor: string
			/**
			 * {0} contribution{{|s}}
			 * @param {string | number | boolean} 0
			 */
			contributions: RequiredParams<'0'>
		}
	}
}

export type TranslationFunctions = {
	header: {
		/**
		 * Home
		 */
		home: () => LocalizedString
		/**
		 * Docs
		 */
		docs: () => LocalizedString
		/**
		 * Blog
		 */
		blog: () => LocalizedString
	}
	footer: {
		/**
		 * Pages
		 */
		pages: () => LocalizedString
		/**
		 * Home
		 */
		home: () => LocalizedString
		/**
		 * Documentation
		 */
		documentation: () => LocalizedString
		/**
		 * Blog
		 */
		blog: () => LocalizedString
		/**
		 * Contribute to Files
		 */
		contributeToFiles: () => LocalizedString
		/**
		 * Give Feedback
		 */
		giveFeedback: () => LocalizedString
		/**
		 * Style Guide
		 */
		styleGuide: () => LocalizedString
		/**
		 * Translations
		 */
		translations: () => LocalizedString
		/**
		 * Contribute to this site
		 */
		contributeToSite: () => LocalizedString
		/**
		 * GitHub Repo
		 */
		gitHubRepo: () => LocalizedString
		/**
		 * Found a bug?
		 */
		foundBug: () => LocalizedString
		/**
		 * Web Team
		 */
		webTeam: () => LocalizedString
		/**
		 * Copyright © 2021 - {thisYear}, The Files Authors
		 */
		copyright: (arg: { thisYear: unknown }) => LocalizedString
		/**
		 * GitHub repository
		 */
		gitHubRepository: () => LocalizedString
		/**
		 * Twitter profile
		 */
		twitterProfile: () => LocalizedString
		/**
		 * Discord server
		 */
		discordServer: () => LocalizedString
	}
	section: {
		download: {
			/**
			 * Downloading...
			 */
			downloading: () => LocalizedString
			/**
			 * Thank you for downloading Files!
			 */
			thankYou: () => LocalizedString
			/**
			 * If the download hasn't started yet, press {link} to start it:
			 */
			comment: (arg: { link: unknown }) => LocalizedString
			/**
			 * here
			 */
			here: () => LocalizedString
			/**
			 * Firefox adds a <code>.xml</code> file extension to the downloaded installer. Remove it before opening the installer.
			 */
			firefoxMessage: () => LocalizedString
			/**
			 * Want to support the creators of Files?
			 */
			wantSupport: () => LocalizedString
			/**
			 * Donate
			 */
			donate: () => LocalizedString
		}
		hero: {
			/**
			 * A modern file explorer that pushes the boundaries of the platform.
			 */
			hook: () => LocalizedString
			/**
			 * Download Files
			 */
			downloadFiles: () => LocalizedString
			/**
			 * Choose download source
			 */
			downloadSource: () => LocalizedString
			/**
			 * View GitHub
			 */
			viewGitHub: () => LocalizedString
			/**
			 * Files is open source!
			 */
			openSource: () => LocalizedString
			winget: {
				/**
				 * Installing Files via winget
				 */
				title: () => LocalizedString
				/**
				 * To download and install Files using {link}, paste the following command into a terminal of your choice:
				 */
				description: (arg: { link: unknown }) => LocalizedString
				/**
				 * Copy Command
				 */
				copyCommand: () => LocalizedString
				/**
				 * Copy
				 */
				copy: () => LocalizedString
				/**
				 * Copied!
				 */
				copied: () => LocalizedString
				/**
				 * Close
				 */
				close: () => LocalizedString
			}
		}
		design: {
			/**
			 * design
			 */
			title: () => LocalizedString
			/**
			 * Power meets beauty.
			 */
			hook: () => LocalizedString
			/**
			 * Explore a beautiful Windows-first design. Manage all your files with increased productivity. Work across multiple folders with tabs. And so much more.
			 */
			description: () => LocalizedString
			/**
			 * Try it out
			 */
			tryItOut: () => LocalizedString
			/**
			 * Design System
			 */
			designSystem: () => LocalizedString
		}
		features: {
			/**
			 * features
			 */
			title: () => LocalizedString
			/**
			 * It already does that.
			 */
			hook: () => LocalizedString
			/**
			 * Cloud files integration? Tabs and multiple layouts? Rich file previews? Files has it covered with robust features you expect from a modern file manager.
			 */
			description: () => LocalizedString
			preview: {
				/**
				 * Name
				 */
				name: () => LocalizedString
				/**
				 * Status
				 */
				status: () => LocalizedString
				/**
				 * Tag
				 */
				tag: () => LocalizedString
				/**
				 * Bit Depth
				 */
				bitDepth: () => LocalizedString
				/**
				 * Dimensions
				 */
				dimensions: () => LocalizedString
				/**
				 * Horizontal Resolution
				 */
				horizontalResolution: () => LocalizedString
				/**
				 * Vertical Resolution
				 */
				verticalResolution: () => LocalizedString
				/**
				 * Item Count
				 */
				itemCount: () => LocalizedString
				/**
				 * Line Count
				 */
				lineCount: () => LocalizedString
				/**
				 * Path
				 */
				path: () => LocalizedString
				/**
				 * Date Created
				 */
				dateCreated: () => LocalizedString
				/**
				 * Date Modified
				 */
				dateModified: () => LocalizedString
				/**
				 * Blue
				 */
				blueTag: () => LocalizedString
				/**
				 * Yellow
				 */
				yellowTag: () => LocalizedString
				/**
				 * Green
				 */
				greenTag: () => LocalizedString
				/**
				 * Gray
				 */
				grayTag: () => LocalizedString
				/**
				 * Orange
				 */
				orangeTag: () => LocalizedString
			}
			cards: {
				cloud: {
					/**
					 * Seamless cloud integration
					 */
					title: () => LocalizedString
					/**
					 * Integration with cloud services such as OneDrive, Google Drive, and iCloud allow you to manage your documents and photos in the cloud, right from the sidebar.
					 */
					description: () => LocalizedString
				}
				preview: {
					/**
					 * File preview
					 */
					title: () => LocalizedString
					/**
					 * Preview documents, photos, and more without opening them. Support for rich previews, syntax highlighting, markdown and video playback is all built in.
					 */
					description: () => LocalizedString
				}
				tag: {
					/**
					 * Tagged Files & Folders
					 */
					title: () => LocalizedString
					/**
					 * Quickly mark and organize your files and folders for later by assigning them colored and named tags for easy identification. You can even add your own custom tags!
					 */
					description: () => LocalizedString
				}
				tabs: {
					/**
					 * Multitask with tabs
					 */
					title: () => LocalizedString
					/**
					 * Avoid multiple windows and keep your desktop clutter-free. Files features a browser-like tabbing interface complete with keyboard shortcuts.
					 */
					description: () => LocalizedString
				}
			}
		}
		themes: {
			/**
			 * themes
			 */
			title: () => LocalizedString
			/**
			 * Distinctly personal.
			 */
			hook: () => LocalizedString
			/**
			 * Have it your way. Files features a fully customizable user interface, right down to the colors and materials. Try custom themes that are built into Files or dive right into the docs and create your own.
			 */
			description: () => LocalizedString
			color: {
				/**
				 * Dark Grey • Light Blue
				 */
				darkGreyLightBlue: () => LocalizedString
				/**
				 * Blue Grey • Neon Green
				 */
				blueGreyNeonGreen: () => LocalizedString
				/**
				 * Purple
				 */
				purple: () => LocalizedString
				/**
				 * Yellow • White
				 */
				yellowWhite: () => LocalizedString
				/**
				 * Cool White • Dark Teal
				 */
				coolWhiteDarkTeal: () => LocalizedString
				/**
				 * Sky Blue
				 */
				skyBlue: () => LocalizedString
			}
		}
		community: {
			/**
			 * community
			 */
			title: () => LocalizedString
			/**
			 * Designed and developed by you.
			 */
			hook: () => LocalizedString
			/**
			 * Files is free and open source software, maintained and designed by a collective of hundreds of contributors.
			 */
			description: () => LocalizedString
			/**
			 * Join the discussion
			 */
			joinDiscussion: () => LocalizedString
			/**
			 * Become a contributer
			 */
			becomeContributor: () => LocalizedString
			/**
			 * {0} contribution{{|s}}
			 */
			contributions: (arg0: string | number | boolean) => LocalizedString
		}
	}
}

export type Formatters = {}
