name: Bug Report
description: Create a bug report to help improve the Files website
labels: [bug]
body:
  - type: checkboxes
    attributes:
      label: Before you start...
      options:
        - label: Have you refreshed the page? You might be using an old version of the site.
          required: true
        - label: Have you checked for an existing issue on this topic? If there is one, post a comment on it instead.
          required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Firefox Beta/Dev/Nightly
        - Chrome Beta/Dev/Canary
        - Safari Beta
        - Microsoft Edge Beta/Dev/Canary
        - Other - list in description
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '....'
        2. Click on '....'
        3. Scroll down to '....'
        4. See the error
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Relevant Assets
      description: |
        A list of assets (errors, screenshots) relevant to this bug.

        Tip: You can attach images or log files by highlighting this area and dragging files into it.
      placeholder: |
        To access the site's log, press Ctrl + Shift + I and open the console tab.
        Errors will be highlighted in red.
